version: '3.8'

services:
  # API Go
  api:
    build: .
    container_name: go-auth-api
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=goauthdb
      - POSTGRES_USER=goauthuser
      - POSTGRES_PASSWORD=secret
      - JWT_SECRET=your-secret-key
    depends_on:
      - db

  # PostgreSQL
  db:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_DB=goauthdb
      - POSTGRES_USER=goauthuser
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
