version: '3.8'

services:
  # API Go
  api:
    build: .
    container_name: go-auth-api
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=dpg-cvh6kq2qgecs73co864g-a.frankfurt-postgres.render.com
      - DB_PORT=5432
      - DB_USER=go_auth_rjmb_user
      - DB_PASSWORD=3giMIX1iapePBIultinRZ2YQvxwUifFT
      - DB_NAME=go_auth_rjmb
      - JWT_SECRET=salutjwtgo