name: Lint Go Code

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.24'

    - name: Set up golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: 'v1.51.2'

    - name: Run golangci-lint
      run: golangci-lint run ./...
